from typing import Dict

FILE_FORMAT_FOLDERS: Dict[str, str] = {
    ".txt": "Text",
    ".md": "Text",
    ".doc": "Documents",
    ".docx": "Documents",
    ".pdf": "Documents",
    ".ppt": "Documents",
    ".heic": "Images",
    ".jpg": "Images",
    ".jpeg": "Images",
    ".png": "Images",
    ".gif": "Images",
    ".mp3": "Music",
    ".wav": "Music",
    ".mp4": "Videos",
    ".avi": "Videos",
    ".mov": "Videos",
    ".wmv": "Videos",
    ".exe": "Executables",
    ".msi": "Executables",
    ".zip": "Zipped",
    ".rar": "Zipped",
    ".tar": "Zipped",
    ".7z": "Zipped",
    ".iso": "Zipped",
    ".csv": "Spreadsheets",
    ".xlsx": "Spreadsheets",
    ".xls": "Spreadsheets",
    ".json": "Scripts",
    ".py": "Scripts",
    ".js": "Scripts",
    ".html": "Scripts",
    ".css": "Scripts",
}
